#!/bin/bash

while [[ -d "/proc/$PPID" && "${1}" -ne "" ]]; do
	sleep 1
done

/usr/bin/cat /boot/intel-ucode.img /boot/initramfs-linux.img > /tmp/initrd.img

/usr/bin/objcopy --add-section .osrel="/usr/lib/os-release" --change-section-vma .osrel=0x20000 --add-section .cmdline="/etc/efistub/cmdline" --change-section-vma .cmdline=0x30000 --add-section .linux="/boot/vmlinuz-linux" --change-section-vma .linux=0x40000 --add-section .initrd="/tmp/initrd.img" --change-section-vma .initrd=0x3000000 "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "/tmp/linuxx64.efi"

/usr/bin/rm /tmp/initrd.img

/usr/bin/sbsign --key /etc/secureboot/keys/db.key --cert /etc/secureboot/certs/db.crt "/tmp/linuxx64.efi" --output "/boot/efi/EFI/arch/linuxx64.efi"

/usr/bin/rm /tmp/linuxx64.efi

/usr/bin/printf "Updated linuxx64.efi\n"
