#!/bin/bash

export TPM2TOOLS_TCTI_NAME=device
export TPM2TOOLS_DEVICE_FILE=/dev/tpmrm0
#export TPM2TOOLS_TCTI_NAME TPM2TOOLS_DEVICE_FILE

source /etc/tpm/tpm.conf
key="$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c32)"

mkdir /tmp/tpmkey/
chmod 600 /tmp/tpmkey/

flush_all() {
	tpm2_flushcontext -s
	tpm2_flushcontext -t
	tpm2_flushcontext -l
}

flush_all

tpm2_evictcontrol -A o -H 0x81000000 -P ${owner_password}

tpm2_pcrlist -L 0x4:0,1,2,3,4,5,6,7 -o /tmp/tpmkey/pcrs
tpm2_createpolicy -P -L 0x4:0,1,2,3,4,5,6,7 -F /tmp/tpmkey/pcrs -f /tmp/tpmkey/policy.digest
tpm2_createprimary -H e -g 0xb -G 0x1 -C /tmp/tpmkey/primary.context -P ${endorsment_password} -K ${key}
tpm2_create -g 0xb -G 0x8 -u /tmp/tpmkey/obj.pub -r /tmp/tpmkey/obj.priv -c /tmp/tpmkey/primary.context -L /tmp/tpmkey/policy.digest -A "noda|adminwithpolicy|fixedparent|fixedtpm" -I ${keyfile} -P ${key}
tpm2_flushcontext -t -c primary.context
tpm2_load -c /tmp/tpmkey/primary.context -u /tmp/tpmkey/obj.pub -r /tmp/tpmkey/obj.priv -C /tmp/tpmkey/load.context -P ${key}
tpm2_evictcontrol -A o -c /tmp/tpmkey/load.context -S 0x81000000 -P ${owner_password}
flush_all

rm -r /tmp/tpmkey/
