# System shell
bindsym $mod+Shift+Return exec $term

# Work toolbox (default)
set $toolbox_work work-f44
bindsym --no-warn $mod+Return exec $term toolbox enter $toolbox_work

# Personal toolbox
set $toolbox_personal personal-f44
bindsym $mod+Ctrl+Return $toolbox_personal
