monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.usb-Burr-Brown_from_TI_USB_Audio_CODEC-*"
      }
    ]
    actions = {
      update-props = {
        device.profile = "pro-audio"
        api.acp.auto-profile = false
        api.acp.auto-port = false
        api.alsa.period-size = 128
        api.alsa.disable-batch = true
        api.alsa.headroom = 0
        latency.internal.rate = 128
      }
    }
  }
]
