monitor.bluez.rules = [
  {
    matches = [
      {
        device.alias  = "FIIO BTR11"
        device.string = "~40:ED:98:1*"
      }
    ]
    actions = {
      update-props = {
        device.profile = "a2dp-sink-aac"
        bluez5.a2dp.ldac.quality = "hq"
      }
    }
  }
]
